steps:
- uses: docker://getpopper/geni:v0.9.9.2
  args: ['./geni_config.py', 'apply']
  secrets:
  - GENI_FRAMEWORK
  - GENI_PROJECT
  - GENI_USERNAME
  - GENI_CERT_DATA
  - GENI_KEY_PASSPHRASE
  - GENI_PUBKEY_DATA

# - uses: docker://getpopper/geni:v0.9.9.2
#   args: ['./geni_config.py', 'destroy']
#   secrets:
#   - GENI_FRAMEWORK
#   - GENI_PROJECT
#   - GENI_USERNAME
#   - GENI_CERT_DATA
#   - GENI_KEY_PASSPHRASE
#   - GENI_PUBKEY_DATA
